name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: sudo apt install libyaml-cpp-dev libatasmart-dev cmake libsensors-dev
    - name: build
      run: |
        mkdir build
        cmake -B build
        cmake --build build
    - name: install
      run: sudo cmake --install ${{ github.workspace }}/build
